[package]
name = "x402_crosschain_confidential_micropayment_manager"
type = "contract"
compiler_version = ">=1.0.0"
authors = [""]

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v3.0.0-devnet.5", directory = "noir-projects/aztec-nr/aztec" }
uint_note = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v3.0.0-devnet.5", directory = "noir-projects/aztec-nr/uint-note" }
compressed_string = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v3.0.0-devnet.5", directory = "noir-projects/aztec-nr/compressed-string" }
contract_instance_registry = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v3.0.0-devnet.5", directory = "noir-projects/noir-contracts/contracts/protocol/contract_instance_registry" }

# External Contracts
aztec_gateway_7683 = { path = "../aztec_gateway_7683" }
att_verifier = { path = "../primus_zktls/att_verifier" }
#partial_att_verifier = { path = "../primus_zktls/partial_att_verifier" } # Currently, this program is moved to the /pending directory due to compile errors-caused by the aztec version mismatch (v3.0.0-devnet.2 and v3.0.0-devnet.5).
basic_business_program = { path = "../primus_zktls/basic_business_program" }