[package]
name = "partial_att_verifier"
type = "contract"
authors = [""]

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v2.0.2", directory="noir-projects/aztec-nr/aztec" }
business_program = { path = "../basic_business_program" }
string_search = { tag= "v0.3.3", git = "https://github.com/noir-lang/noir_string_search"}
